"""Generate LaTeX tables from the analysis CSVs for the thesis.

Outputs to `master/thesis/tables/`. Each table is a standalone .tex file
that can be \\input{} into the chapters.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

OUT = PROJECT_ROOT / "master" / "thesis" / "tables"
OUT.mkdir(parents=True, exist_ok=True)


_HEADER = (
    "% Auto-generated by master/generate_thesis_tables.py\n"
    "% Do not edit by hand — re-run the generator instead.\n"
)


def _write(name, latex):
    (OUT / f"{name}.tex").write_text(_HEADER + latex)


def table_phase1_summary():
    """Per-model test accuracy + bootstrap CI + AUC + ECE."""
    p = PROJECT_ROOT / "master" / "results" / "per_model_summary.csv"
    if not p.exists():
        return
    df = pd.read_csv(p)
    rows = []
    for _, r in df.iterrows():
        ci = f"[{r['test_acc_ci_lo']*100:.2f}, {r['test_acc_ci_hi']*100:.2f}]"
        rows.append(
            f"{r['model']} & {r['test_accuracy']*100:.2f} & {ci} & "
            f"{r['test_auc']:.4f} & {r['ece_raw']:.4f} & "
            f"{r['ece_after_temp_scale']:.4f} & {r['temperature']:.2f} \\\\"
        )
    body = "\n".join(rows)
    latex = (
        "\\begin{table}[t]\n"
        "  \\centering\n"
        "  \\caption{Per-model test performance with bootstrap 95\\% confidence "
        "intervals on the held-out test set ($N = 550$). ECE is reported before "
        "and after temperature scaling fit on the validation set.}\n"
        "  \\label{tab:phase1-summary}\n"
        "  \\small\n"
        "  \\begin{tabular}{lcccccc}\n"
        "    \\toprule\n"
        "    Model & Test acc (\\%) & 95\\% CI & AUC & ECE raw & ECE TS & $T$ \\\\\n"
        "    \\midrule\n"
        f"    {body}\n"
        "    \\bottomrule\n"
        "  \\end{tabular}\n"
        "\\end{table}\n"
    )
    _write("tab_phase1_summary", latex)


def table_phase1_mcnemar():
    p = PROJECT_ROOT / "master" / "results" / "mcnemar_pairwise.csv"
    if not p.exists():
        return
    df = pd.read_csv(p)
    rows = []
    for _, r in df.iterrows():
        sig = "Yes" if r['pvalue'] < 0.05 else "No"
        rows.append(
            f"{r['model_a']} vs {r['model_b']} & {int(r['b'])} & {int(r['c'])} & "
            f"{r['statistic']:.2f} & {r['pvalue']:.4f} & {sig} \\\\"
        )
    body = "\n".join(rows)
    latex = (
        "\\begin{table}[t]\n"
        "  \\centering\n"
        "  \\caption{Pairwise McNemar tests on the binary test set ($N = 550$). "
        "$b$ counts predictions where A is correct and B wrong; $c$ vice versa. "
        "$p < 0.05$ indicates a statistically significant difference in error rates.}\n"
        "  \\label{tab:phase1-mcnemar}\n"
        "  \\scriptsize\n"
        "  \\begin{tabular}{lccccc}\n"
        "    \\toprule\n"
        "    Comparison & $b$ & $c$ & $\\chi^2$ & $p$-value & Significant? \\\\\n"
        "    \\midrule\n"
        f"    {body}\n"
        "    \\bottomrule\n"
        "  \\end{tabular}\n"
        "\\end{table}\n"
    )
    _write("tab_phase1_mcnemar", latex)


def table_phase2_kfold():
    p = PROJECT_ROOT / "master" / "results" / "kfold" / "resnet50_fold_summary.csv"
    pj = PROJECT_ROOT / "master" / "results" / "kfold" / "resnet50_kfold_summary.json"
    if not p.exists() or not pj.exists():
        return
    df = pd.read_csv(p)
    with open(pj) as f:
        s = json.load(f)
    rows = []
    for _, r in df.iterrows():
        rows.append(
            f"{int(r['fold'])} & {int(r['epochs_trained'])} & "
            f"{r['best_val_accuracy']*100:.2f} & {r['test_accuracy']*100:.2f} & "
            f"{r['test_auc']:.4f} & {r['elapsed_sec']/60:.1f} \\\\"
        )
    body = "\n".join(rows)
    mean_acc = s['test_accuracy_mean'] * 100
    std_acc = s['test_accuracy_std'] * 100
    latex = (
        "\\begin{table}[t]\n"
        "  \\centering\n"
        "  \\caption{ResNet50 5-fold cross-validation results. The held-out test "
        "set ($N = 550$) is fixed across folds; only the train/val split varies. "
        f"Mean test accuracy: ${mean_acc:.2f} \\pm {std_acc:.2f}$\\%.}}\n"
        "  \\label{tab:phase2-kfold}\n"
        "  \\small\n"
        "  \\begin{tabular}{ccccccc}\n"
        "    \\toprule\n"
        "    Fold & Epochs & Best val (\\%) & Test acc (\\%) & Test AUC & Time (min) \\\\\n"
        "    \\midrule\n"
        f"    {body}\n"
        "    \\bottomrule\n"
        "  \\end{tabular}\n"
        "\\end{table}\n"
    )
    _write("tab_phase2_kfold", latex)


def table_phase3_summary():
    p = PROJECT_ROOT / "master" / "results" / "multiclass" / "summary.csv"
    if not p.exists():
        return
    df = pd.read_csv(p)
    rows = []
    for _, r in df.iterrows():
        rows.append(
            f"{r['model']} & {r['test_accuracy']*100:.2f} & {r['qwk']:.4f} & "
            f"{r['ordinal_distance']:.3f} & {r['macro_f1']:.4f} & "
            f"{r['weighted_f1']:.4f} & {r['ece_raw']:.4f} \\\\"
        )
    body = "\n".join(rows)
    latex = (
        "\\begin{table}[t]\n"
        "  \\centering\n"
        "  \\caption{5-stage DR grading on the multi-class held-out test set "
        "($N = 550$). QWK = quadratic-weighted kappa; ord-dist is the mean "
        "$|y - \\hat{y}|$ of misclassifications.}\n"
        "  \\label{tab:phase3-summary}\n"
        "  \\small\n"
        "  \\begin{tabular}{lcccccc}\n"
        "    \\toprule\n"
        "    Model & Acc (\\%) & QWK & Ord-dist & Macro F1 & Weighted F1 & ECE \\\\\n"
        "    \\midrule\n"
        f"    {body}\n"
        "    \\bottomrule\n"
        "  \\end{tabular}\n"
        "\\end{table}\n"
    )
    _write("tab_phase3_summary", latex)


def table_phase3_per_class():
    p = PROJECT_ROOT / "master" / "results" / "multiclass" / "resnet50_5class_per_class.csv"
    if not p.exists():
        return
    df = pd.read_csv(p)
    rows = []
    for _, r in df.iterrows():
        rows.append(
            f"{r['class']} & {int(r['support'])} & {r['precision']:.2f} & "
            f"{r['recall']:.2f} & {r['f1']:.2f} \\\\"
        )
    body = "\n".join(rows)
    latex = (
        "\\begin{table}[t]\n"
        "  \\centering\n"
        "  \\caption{ResNet50 5-class per-class breakdown on the held-out "
        "test set ($N = 550$). The model detects ``No DR'' near-perfectly "
        "but is weaker on minority severities (Mild, Severe, PDR), where "
        "uncertainty estimation is most valuable.}\n"
        "  \\label{tab:phase3-per-class}\n"
        "  \\small\n"
        "  \\begin{tabular}{lcccc}\n"
        "    \\toprule\n"
        "    Class & Support & Precision & Recall & F1 \\\\\n"
        "    \\midrule\n"
        f"    {body}\n"
        "    \\bottomrule\n"
        "  \\end{tabular}\n"
        "\\end{table}\n"
    )
    _write("tab_phase3_per_class", latex)


def table_phase3_conformal():
    p = PROJECT_ROOT / "master" / "results" / "multiclass" / "resnet50_5class_conformal.csv"
    if not p.exists():
        return
    df = pd.read_csv(p)
    rows = []
    for _, r in df.iterrows():
        cov = r['target_coverage']
        rows.append(
            f"{r['score'].upper()} & {cov*100:.0f} & {r['coverage']*100:.2f} & "
            f"{r['mean_size']:.2f} & {r['conditional_coverage']} \\\\"
        )
    body = "\n".join(rows)
    latex = (
        "\\begin{table}[t]\n"
        "  \\centering\n"
        "  \\caption{Conformal prediction on the ResNet50 5-class model. "
        "The empirical marginal coverage tracks the target. Per-class "
        "conditional coverage is the fraction of true-class examples whose "
        "prediction set contains the true label, ordered as "
        "[No\\,DR, Mild, Moderate, Severe, PDR].}\n"
        "  \\label{tab:phase3-conformal}\n"
        "  \\scriptsize\n"
        "  \\begin{tabular}{cccccp{4.5cm}}\n"
        "    \\toprule\n"
        "    Score & Target (\\%) & Empirical (\\%) & Mean size & Per-class coverage \\\\\n"
        "    \\midrule\n"
        f"    {body}\n"
        "    \\bottomrule\n"
        "  \\end{tabular}\n"
        "\\end{table}\n"
    )
    _write("tab_phase3_conformal", latex)


def table_phase3_compare_bachelor():
    """Hand-written comparison of bachelor binary vs master multi-class scope."""
    latex = (
        "\\begin{table}[t]\n"
        "  \\centering\n"
        "  \\caption{Scope comparison: bachelor binary classifier vs master "
        "5-stage uncertainty-aware system.}\n"
        "  \\label{tab:bachelor-vs-master}\n"
        "  \\small\n"
        "  \\begin{tabular}{lll}\n"
        "    \\toprule\n"
        "    Aspect & Bachelor (binary) & Master (5-stage + UQ) \\\\\n"
        "    \\midrule\n"
        "    Best test accuracy & 96\\% (single split) & 77\\% (5-class, harder) \\\\\n"
        "    Clinical task & ``Has DR / no DR'' & ``How severe?'' \\\\\n"
        "    Statistical guarantees & --- & Conformal coverage 95\\% \\\\\n"
        "    Calibration analysis & --- & ECE = 0.030 \\\\\n"
        "    Ordinal evaluation & N/A & QWK = 0.847 \\\\\n"
        "    Per-class transparency & N/A & F1 per stage \\\\\n"
        "    Out-of-distribution & --- & 4 detection methods \\\\\n"
        "    Bayesian uncertainty & --- & MC Dropout (T=30) \\\\\n"
        "    Significance testing & --- & McNemar + bootstrap CI \\\\\n"
        "    Generalisation & 1 split & 5-fold CV ($\\sigma$=0.18\\,pp) \\\\\n"
        "    Clinical refer rule & --- & Set size $\\geq 3 \\to$ refer \\\\\n"
        "    \\bottomrule\n"
        "  \\end{tabular}\n"
        "\\end{table}\n"
    )
    _write("tab_bachelor_vs_master", latex)


def main():
    table_phase1_summary()
    table_phase1_mcnemar()
    table_phase2_kfold()
    table_phase3_summary()
    table_phase3_per_class()
    table_phase3_conformal()
    table_phase3_compare_bachelor()
    print(f"Wrote LaTeX tables to {OUT}/")


if __name__ == "__main__":
    main()
